package:
  name: scikit-garden
  version: "0.1.3"

source:
  git_url: https://github.com/messDiv/scikit-garden

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - numpy >=1.20
    - scipy
    - cython >=0.28
    - scikit-learn
  run:
    - cython
    - numpy >=1.20
    - scipy
    - scikit-learn

about:
  home: https://github.com/scikit-garden/scikit-garden
  license: GPLv3
  summary: A garden for Scikit-Learn compatible decision trees and forests, patched for scikit-learn 0.23 compatibility
