package:
  name: mess
  version: "0.1.1"

source:
  git_url: https://github.com/messDiv/MESS
  git_tag: master

build:
  number: 11
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - msprime
    - ipyparallel
    - scipy
    - cython
    - cloudpickle
    - ipython
    - numpy
    - pandas
    - svgwrite
    - mpmath
    - certifi
    - rpy2
    - boruta_py
    - scikit-garden
    - numpy >=1.20
  run:
    - python >=3.6
    - cloudpickle
    - setuptools
    - ipython
    - ipyparallel
    - cython
    - scipy
    - nbconvert
    - joblib
    - jupyter_client
    - jupyter
    - notebook
    - pandas
    - msprime
    - mpmath
    - rpy2 >=3.0
    - matplotlib
    - boruta_py
    - scikit-garden
    - tzlocal
    - matplotlib
    - imagemagick
    - seaborn
    - toytree
    - numpy >=1.20

  commands:
    - MESS -v

about:
  home: https://github.com/messDiv/MESS
  license: GPLv3
  summary: Massive Eco-Evolutionary Synthesis Simulations
